name: Use Secret Scanning Workflow from sec-checks repo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-secret-scanning:
    uses: zahidali81/sec-checks/.github/workflows/secrets-scanner.yml@main
    with:
      runs_on: ubuntu-latest
